name: Test Rust Code

on:
  pull_request:
    paths:
      - "rust/**/*.rs"
      - "rust/**/Cargo.toml"
      - "rust/Cargo.lock"
      - "noxfile.py"
      - ".github/workflows/test-rust.yml"
  push:
    branches:
      - main
      - master
    paths:
      - "rust/**/*.rs"
      - "rust/**/Cargo.toml"
      - "rust/Cargo.lock"
      - "noxfile.py"
      - ".github/workflows/test-rust.yml"

  workflow_dispatch:

jobs:
  test-rust-msrv:
    name: Test Rust MSRV 1.83
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Rust 1.83
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.83"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Run Rust MSRV tests
        run: uvx nox -s tests-rust-msrv

  test-rust:
    name: Run Rust Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: "ubuntu-latest" }
          - { os: "macos-latest" }
          - { os: "windows-latest" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust/"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Run Rust tests
        run: uvx nox -s tests-rust
