name: Test Rust Code

on:
  pull_request:
    paths:
      - "rust/**/*.rs"
      - "Cargo.toml"
      - "noxfile.py"
      - ".github/workflows/test-rust.yml"
  push:
    branches:
      - main
      - master
    paths:
      - "rust/**/*.rs"
      - "Cargo.toml"
      - "noxfile.py"
      - ".github/workflows/test-rust.yml"

  workflow_dispatch:

jobs:
  test-rust:
    name: Run Rust Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: "ubuntu-latest" }
          - { os: "macos-latest" }
          - { os: "windows-latest" }

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2
        with:
          workspaces: "rust/"

      - name: Set up uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Run Rust tests
        run: uvx nox -s tests-rust
